vich_uploader:
    db_driver: orm

    mappings:
        users_images:
           uri_prefix: upload/images/users
           upload_destination: '%kernel.project_dir%/public/upload/images/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        employes_images:
           uri_prefix: upload/images/employes
           upload_destination: '%kernel.project_dir%/public/upload/images/employes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
